language: php
php:
- '5.5'
script: echo "We don't have tests yet :("
before_deploy:
  - sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: secure: L81IeU6700f2QX+ttT5XCmgTNE9aM6mzHiwAmvdzo0sp7feBWy+J8VLYughFC5y2MHYdbf5K5qA5fK2OZw9OwytQ46iPbMGyc0T2tW3ruDmmaIZExM6HkFeY92Htfvi39cHlpe2WQM97FtY0BE6SaqEQV5ap8tbxB9Q72yuk2j+8DuioVgbzhl4uAl3br+nHGYh9tWvhewI0Z/XyClZ6INa1mo94mvIkTuIv4obefXSIozZQsnBgUo7aw0xGjzbtJMagZ2FqIZ80765l7IIqyyD6g6WDW9EVGACLL0tslwmMS3NutpRz3VaoJlnEZal/U36FZIckQATQIIVBzt+qFXHewNAFJBeaWeSINb/MoT0YW+sInt2ZHEInK8jk8rYiRhhCWIgTPqvXOqRTUbyvyTBIy3qiYk7yyQicnHfzjD3qkTrgiIaDcK0LfeKwjGXV1n7tjoefbHHcjxqhs4PU2dHQGfENmX/aiDGpwGCP0ut5OObB2ZLkV/dbUpCYkrFseMpnMBOszDxXYjJyyt45Q04cnirRSZ8Hqd62VVztpsXM04U3HCBywm2D+JMwGI2yDIDuq9ftKw5JTDkzd7Oj9Xx7J+KkAkHsZXGpndLqhmSr6N10eEoLj7PHWVsMR1bfzIzYdZE66ziUNCH+eGbhKCn9P52/rlZH6D20f/rgXdk=
  file: plugin-woocommerce-onepay-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-woocommerce-onepay
    tags: true
