language: php
php:
- '5.5'
script: echo "We don't have tests yet :("
before_deploy:
  - sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: fPN9fG7gP0KZX36pUXZz/R5/s5g9hBp8UTTHzSlNDxrFAqq97OV4CLsxp2BjDU7dtG3vOIC+nH+AgkuZ8QmYfoyAcScDvUg4D3llHi1pPYkJ/oZRUSpe4WeI5YK5l73PDPJyBLZPvNedD8jJGUeVjjGuL+Lfe9iB7LppjJTHVaEhgneScPI4XPyV2bAIO3GKPIcvrZ2FIDuNXgWSFBB47Er/K/vVL7xL3KqdI1qhU96cbjTNfOCujb6NFUIn1pVVn/XzwnqTtnY14V2lLSXS4IeoQRFG6C/73kLZjsQVf2dcPuDd4u7GAa++mDfDxY552bMdBEjAljmp/uY06NtxuitTmfOBZhjN3frjmHrmL4fEIF+BHbb8BDQoZSjmnSReOA+XCv19kvRnHuVksws38Rwe24aKhuq8H3hdDk/VmuWyNkSuFyqFTMn4GtMieahI4KEeZJUyZ77hagWFzQxi4qiY4cQD50fg00xC7k7pdEuSUmqMgRdDww2RVEEMvRZbg4WH03HYNwNSn/KQfNPfHmrDVssZRv7a+/RZcxiav0MrCRrSFgp7ynK4AmRoe0rgYMa6BwzUUb5L7TBsV7nnT1hmi06jWD0q/3HRD++upW8CN9EniSrLlubA72gK5oRU+//SBaP6Vmc4j2M5MsMPRF872MYUkK6R/YLRm8ecEIU=
  file: plugin-woocommerce-onepay-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-woocommerce-onepay
    tags: true
